# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logsonic < Formula
  desc "Desktop-first log analytics with full-text search and Grok parsing"
  homepage "https://github.com/logsonic/logsonic"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/logsonic/logsonic/releases/download/v1.2.0/logsonic_1.2.0_darwin_amd64.tar.gz"
      sha256 "667fe4651e58a9a6bf00f60a736e923b402063f45320b1fc708f54762ee3c196"

      def install
        bin.install "logsonic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/logsonic/logsonic/releases/download/v1.2.0/logsonic_1.2.0_darwin_arm64.tar.gz"
      sha256 "9e2af9036857e37ccb9c4611adf9f5484b3c2a2776c1d77cd3a7c4454e459dc3"

      def install
        bin.install "logsonic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/logsonic/logsonic/releases/download/v1.2.0/logsonic_1.2.0_linux_amd64.tar.gz"
      sha256 "59290e287ddfff39dea6c187b3941dea860d062242d3f125199fa819a80cf9e6"
      def install
        bin.install "logsonic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logsonic/logsonic/releases/download/v1.2.0/logsonic_1.2.0_linux_arm64.tar.gz"
      sha256 "aaf4d7e85dcdb0255dbbc08067b2e41b57dd7aeb08eaa19d7fa5927658aeb434"
      def install
        bin.install "logsonic"
      end
    end
  end

  test do
    assert_match "LogSonic", shell_output("#{bin}/logsonic -help")
  end
end
