# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Logsonic < Formula
  desc "Desktop-first log analytics with full-text search and Grok parsing"
  homepage "https://github.com/logsonic/logsonic"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/logsonic/logsonic/releases/download/v1.1.1/logsonic_1.1.1_darwin_amd64.tar.gz"
      sha256 "ff646fb3ad7860c139d05fffc108414aa710a9ddf7d5e35d864a76a9380fb022"

      def install
        bin.install "logsonic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/logsonic/logsonic/releases/download/v1.1.1/logsonic_1.1.1_darwin_arm64.tar.gz"
      sha256 "f9a591153a8755e25cb24a2c1f32ce9b4103cf5c669ec9843babf88445023d5f"

      def install
        bin.install "logsonic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/logsonic/logsonic/releases/download/v1.1.1/logsonic_1.1.1_linux_amd64.tar.gz"
      sha256 "9a40dd35cc8d431a0705c4f6068ad978fb29631d8956de10746bb45dbe054f4e"
      def install
        bin.install "logsonic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logsonic/logsonic/releases/download/v1.1.1/logsonic_1.1.1_linux_arm64.tar.gz"
      sha256 "febec96875760256866034608bc4e7506ef5c05df47813531bc739bbced9b829"
      def install
        bin.install "logsonic"
      end
    end
  end

  test do
    assert_match "LogSonic", shell_output("#{bin}/logsonic -help")
  end
end
